/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MigrateKeytarResult {
  migrated: boolean
  error?: string
}

export declare namespace passwords {
  /**
   * Delete the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function deletePassword(service: string, account: string): Promise<void>
  /**
   * Fetch the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function getPassword(service: string, account: string): Promise<string>
  /** Check if OS secure storage is available. */
  export function isAvailable(): Promise<boolean>
  /**
   * Migrate a credential that was stored by keytar (UTF-8 blob) to the new UTF-16 format
   * used by desktop_core on Windows. No-ops on non-Windows platforms.
   *
   * Returns `{ migrated: true }` if a migration was performed.
   * Returns `{ migrated: false }` if the credential does not exist or is already in the correct
   * format. Returns `{ migrated: false, error: "<reason>" }` if a Credential Manager failure
   * prevented migration. Never throws.
   */
  export function migrateKeytarPassword(service: string, account: string): Promise<MigrateKeytarResult>
  /**
   * The error message returned when a password is not found during retrieval or deletion.
   * Re-exported from desktop_core so JS callers have a single authoritative source.
   */
  export const PASSWORD_NOT_FOUND: string
  /**
   * Read a credential that was stored by keytar (UTF-8 blob) and return the correctly
   * re-encoded string value without writing anything. Returns null if the credential does
   * not exist. No-op on non-Windows platforms (returns null).
   */
  export function readKeytarPassword(service: string, account: string): Promise<string | null>
  /** Save the password to the keychain. Adds an entry if none exists, otherwise updates it. */
  export function setPassword(service: string, account: string, password: string): Promise<void>
}
