/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MigratedLegacyAccount {
  legacyAccount: string
  flatKey: string
}

export interface MigrateKeytarResult {
  migrated: boolean
  log: string
}

export interface MigrateLegacyResult {
  accounts: Array<MigratedLegacyAccount>
  log: string
}

export declare namespace passwords {
  /**
   * Delete the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function deletePassword(service: string, account: string): Promise<void>
  /**
   * Fetch the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function getPassword(service: string, account: string): Promise<string>
  /** Check if OS secure storage is available. */
  export function isAvailable(): Promise<boolean>
  /**
   * Migrate a credential that was stored by keytar (UTF-8 blob) to the new UTF-16 format
   * used by desktop_core on Windows. No-ops on non-Windows platforms.
   *
   * Returns true if a migration was performed, false if the credential was already in the
   * correct format or does not exist.
   */
  export function migrateKeytarPassword(service: string, account: string): Promise<MigrateKeytarResult>
  /**
   * Like migrate_keytar_password but reads from `old_account` and writes to `new_account`.
   * Used by the 3→5 state migration to rename "{userId}_ldapPassword" → "secretLdap" etc.
   * while simultaneously re-encoding from UTF-8 (keytar) to UTF-16 (desktop_core).
   * No-ops on non-Windows platforms.
   */
  export function migrateKeytarPasswordAs(service: string, oldAccount: string, newAccount: string): Promise<MigrateKeytarResult>
  /**
   * Finds any credentials stored by keytar under legacy "{prefix}_*" account names
   * (e.g. "{orgId}_ldapPassword"), migrates their blobs from UTF-8 to UTF-16, and
   * saves them under the canonical flat key (e.g. "secretLdap").
   *
   * Returns an array of objects with `{ legacyAccount, flatKey }` for each migrated entry.
   * No-ops on non-Windows platforms and returns an empty array.
   */
  export function migrateLegacyKeytarAccounts(service: string): Promise<MigrateLegacyResult>
  /**
   * The error message returned when a password is not found during retrieval or deletion.
   * Re-exported from desktop_core so JS callers have a single authoritative source.
   */
  export const PASSWORD_NOT_FOUND: string
  /** Save the password to the keychain. Adds an entry if none exists, otherwise updates it. */
  export function setPassword(service: string, account: string, password: string): Promise<void>
}
