/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MigratedLegacyAccount {
  legacyAccount: string
  flatKey: string
}
export declare namespace passwords {
  /**
   * Delete the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function deletePassword(service: string, account: string): Promise<void>
  /**
   * Fetch the stored password from the keychain.
   * Throws an Error with message PASSWORD_NOT_FOUND if the password does not exist.
   */
  export function getPassword(service: string, account: string): Promise<string>
  /** Check if OS secure storage is available. */
  export function isAvailable(): Promise<boolean>
  /**
   * Migrate a credential that was stored by keytar (UTF-8 blob) to the new UTF-16 format
   * used by desktop_core on Windows. No-ops on non-Windows platforms.
   *
   * Returns true if a migration was performed, false if the credential was already in the
   * correct format or does not exist.
   */
  export function migrateKeytarPassword(service: string, account: string): Promise<boolean>
  /**
   * Like migrateKeytarPassword but reads from oldAccount and writes to newAccount.
   * Used by the 3→5 state migration to rename legacy prefixed keys to flat keys
   * while re-encoding from UTF-8 (keytar) to UTF-16 (desktop_core).
   * No-ops on non-Windows platforms.
   */
  export function migrateKeytarPasswordAs(service: string, oldAccount: string, newAccount: string): Promise<boolean>
  /**
   * Enumerates credentials stored under legacy "{orgId}_*" keytar account names,
   * migrates their blobs from UTF-8 to UTF-16, and saves them under the canonical
   * flat key names. Returns an array of migrated entries.
   * No-ops on non-Windows platforms and returns an empty array.
   */
  export function migrateLegacyKeytarAccounts(service: string): Promise<Array<MigratedLegacyAccount>>
  /**
   * The error message returned when a password is not found during retrieval or deletion.
   * Re-exported from desktop_core so JS callers have a single authoritative source.
   */
  export const PASSWORD_NOT_FOUND: string
  /** Save the password to the keychain. Adds an entry if none exists, otherwise updates it. */
  export function setPassword(service: string, account: string, password: string): Promise<void>
}
